package Models;
// Generated May 9, 2020 2:34:12 PM by Hibernate Tools 4.3.1



/**
 * Bookcategory generated by hbm2java
 */
public class Bookcategory  implements java.io.Serializable {


     private String categoryid;
     private String categoryname;

    public Bookcategory() {
    }

	
    public Bookcategory(String categoryid) {
        this.categoryid = categoryid;
    }
    public Bookcategory(String categoryid, String categoryname) {
       this.categoryid = categoryid;
       this.categoryname = categoryname;
    }

    
    public String getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(String categoryid) {
        this.categoryid = categoryid;
    }
    public String getCategoryname() {
        return this.categoryname;
    }
    
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }




}


